/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public static int[] roll(int n){
        int[] rollSaves = new int[n];

        for(int i = 0; i < n - 1; i++){
            int diceRoll = (int)(Math.random()*6) + 1;
            rollSaves[i] = diceRoll;


        }
        return rollSaves;

    }


    public static boolean containsDuplicates(int[] arr) {

        for (int i = 0; i < arr.length - 1; i++) {
            for (int j = i + 1; j < arr.length; j++) {
                if (arr[i] == arr[j]) {
                    return false;
                }
            }

        }

return true;
    }


    public static int averageCount(int[][] arr){

        int lowestAvg = 0;
        for(int i = 0; i < arr.length; i++ ){
            int count = 0;

            for(int j = 0; j < arr[0].length; j++){

                count += arr[i][j];

            }

           int avg = count / arr[i].length;

            System.out.println(avg);
            if(lowestAvg >  avg || lowestAvg == 0) {
                lowestAvg = avg;

            }

        }

       return lowestAvg;
    }

}
